server:
  port: 8080
  servlet:
    context-path: /benchmark
  tomcat:
    threads:
      max: 400
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379